In [ ]:
import numpy as np
from copy import deepcopy

In [ ]:
def square(x):
  total = 0
  for i in x:
    total = total + i**2
  return total

In [ ]:
def poly(x):
  return (x**2 - 2.0)*(x**2 - 2.0)

In [ ]:
class problem:
  def __init__(self):
    self.number_of_genes = 1
    self.min = 0
    self.max = 2
    self.cost_function = poly


In [ ]:
class Parameters:
  def __init__(self):
    self.population = 1000
    self.maximum_number_of_generations = 1000
    self.crossover_exploration = 0.1
    self.mutation_rate = 0.2
    self.mutation_range = 0.1
    self.child_factor = 1


In [ ]:
class Individual:
  def __init__(self, prob):
    self.chromosome =np.random.uniform(prob.min, prob.max, prob.number_of_genes)
    self.cost = prob.cost_function(self.chromosome)

  def Crossover(self, other, epsilon):
    child1 = deepcopy(self)
    child2 = deepcopy(other)

    alpha = np.random.uniform(-epsilon,1+epsilon)


    child1.chromosome = alpha*self.chromosome + (1-alpha)*other.chromosome
    child2.chromosome = (1-alpha)*self.chromosome + alpha*other.chromosome
    return child1, child2

  def Mutate(self,mutation_rate,mutation_range):
    for i in range(len(self.chromosome)):
      if np.random.uniform(0,1) < mutation_rate:
        self.chromosome[i] += np.random.randn()*mutation_range


In [ ]:
p = problem()

In [ ]:
i2 = Individual(p)

In [ ]:
i2.cost

np.float64(339.67700220492395)

In [ ]:
c1,c2 = i1.Crossover(i2, 0.1)

In [ ]:
p = problem()

In [ ]:
p.max

10

In [ ]:
i1 = Individual(p)
i2 = Individual(p)

In [ ]:
i1.cost


np.float64(205.99206728417911)

In [ ]:
i2.cost

np.float64(456.3367743425806)

In [ ]:
i1.chromosome

array([ 6.20880552, -9.14225674,  2.28595239,  2.81349076,  1.2906201 ,
       -5.11756363,  8.96086992,  6.80813238])

In [ ]:
i2.chromosome

array([-7.91927944,  2.33574457, -8.82706262, -7.77094596,  7.0643057 ,
        6.17816038, -8.49333159,  6.35566855])

In [ ]:
def get_parents(population):
  index1 = np.random.randint(0, len(population))
  index2 = np.random.randint(0, len(population))
  if index1 == index2:
    return get_parents(population)
  parent1 = population[index1]
  parent2 = population[index2]
  return parent1, parent2

In [ ]:
def run_genetic(prob, params):
  # Read in variables from problem and the parameters
  number_in_population = params.population
  number_of_genes = prob.number_of_genes
  cost_function = prob.cost_function
  maximum_number_of_generations = params.maximum_number_of_generations
  crossover_exploration = params.crossover_exploration
  mutation_rate = params.mutation_rate
  mutation_range = params.mutation_range
  children_per_generation = number_in_population * params.child_factor
  # Generate the initial population
  population = []
  best_solution = Individual(prob)
  best_cost = np.inf
  for i in range(number_in_population):
    new_individual = Individual(prob)
    if new_individual.cost < best_cost:
      best_cost = new_individual.cost
      best_solution = deepcopy(new_individual)
    population.append(Individual(prob))


  # Iterate from here for each generation
  for generation in range(maximum_number_of_generations):
      # produce children until correct amount
      children = []
      while len(children) < children_per_generation:
          # choose parents
          parent1, parent2 = get_parents(population)
          # mate parents
          child1, child2 = parent1.Crossover(parent2,crossover_exploration)
              # mate producing 2 children (Crossover)
              # mutate the children
          child1.Mutate(mutation_rate, mutation_range)
          child2.Mutate(mutation_rate, mutation_range)
              # calculate child cost
          child1.cost = cost_function(child1.chromosome)
          child2.cost = cost_function(child2.chromosome)
          children.append(child1)
          children.append(child2)
              # add to population
      population += children
      # cull the population
      population = sorted(population, key=lambda x: x.cost)
      population = population[:number_in_population]
      if population[0].cost<best_solution.cost:
        best_solution = deepcopy(population[0])
        best_cost = best_solution.cost

      print(best_cost)


  return best_solution


In [ ]:
best =run_genetic(p, Parameters())

In [ ]:
best.cost

np.float64(29.738105189492906)

In [ ]:
best.chromosome

array([ 0.73309113, -0.6745819 , -1.81382774, -0.41173786, -4.56265077,
        1.6464682 , -1.12857811, -0.69555342])

In [ ]:
p1 = problem()
par1 = Parameters()

In [ ]:
run_genetic(p1, par1)

[1.59516429e-07]
[1.59516429e-07]
[1.59516429e-07]
[5.04285093e-09]
[5.04285093e-09]
[9.12937937e-10]
[9.12937937e-10]
[7.77117845e-11]
[7.77117845e-11]
[4.36113976e-12]
[1.40742425e-12]
[6.01224302e-13]
[3.73808419e-14]
[3.73808419e-14]
[1.19777331e-14]
[1.17887528e-15]
[6.14217367e-16]
[1.12335212e-18]
[1.12335212e-18]
[1.12335212e-18]
[1.12335212e-18]
[5.56149615e-20]
[1.47669255e-20]
[1.03598351e-21]
[1.03598351e-21]
[1.03598351e-21]
[6.96184998e-23]
[1.35534389e-25]
[1.35534389e-25]
[1.35534389e-25]
[3.33293732e-29]
[3.33293732e-29]
[3.33293732e-29]
[3.33293732e-29]
[3.33293732e-29]
[3.33293732e-29]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-31]
[1.97215226e-3

In [ ]:
o = Out[75]

In [ ]:
o.cost

array([1.97215226e-31])

In [ ]:
o.chromosome

array([1.41421356])